project:
  type: website

website:
  title: "Marcus Wild"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Wild CV March 2025.pdf
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

